using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StringLibrary : MonoBehaviour
{
    public int curseLenght;
    public int messageLength;

    public List<string> curseText = new List<string>(new string[]
    {
        "Bosses have their minds set on getting that for the company.",
        "Yeah, it'll surely skyrocket their careers.",
        "Upper management will be ecstatic.",
        "They've been looking for an upper edge for decades now.",
        "And if this works out…",
        "...and someone can extract it finally…",
        "...then they'll be the fucking employee of the decade!",
        "Karen has a plan how to do it.",
        "I heard she has had…",
        "...hushed meetings with Rex lately.",
        "But HR is breathing down on them though.",
        "They are looking for any mistake in the plan, to shut it down.",
        "If it gets too risky, then yeah, that'd be best.",
        "I don't want to end up on the street…",
        "...if the police shuts this place down for good.",
        "Although no local police can really shut down the whole thing.",
        "This shit is like Illuminati!",
        "It will just go on somewhere else…",
        "... until they get a new foothold in here.",
        "But I can't take that risk.",
        "Little low-levels like me could end up behind bars.",
        "And that's just bullshit!",
        "I know too much already, I never wanted to know.",
        "I heard Karen say she found a potential source.",
        "And Rex, he was… smiling the other day.",
        "So they must be really onto something.",
        "Maybe I should just tell HR what I know…",
        "... before things get too hot.",
        "Although if I leave them be and they succeed…",
        "... something good could trickle down as well.",
        "Rewards could be amazing!",
        "But at what cost?",
        "When I went to the office basement…",
        "...I swear I heard screams in there.",
        "Sure, it could have been something else!",
        "Any noise can be distorted within those echoes.",
        "Sure it was just a car screeching off.",
        "But it.. did sound like a scream…",
        "...that cut off, abruptly.",
        "Upper management have been after souls…",
        "... they're obsessed with them.",
        "Souls are immortal...",
        "...if you want to believe in shit like that.",
        "And management sure does.",
        "Souls trapped in jars, sounds… icky.",
        "Karen got too involved with nursing homes.",
        "They got too suspicious.",
        "I have my own suspicions…",
        "...on where she now gets her subjects.",
        "Rex doesn't care where they come from.",
        "That fellow sure is result-oriented.",
        "That could get him far in the company.",
        "Management really does like results.",
        "But if people keep disappearing…",
        "...someone will get a sniff of what's going on.",
        "Karen is too ambitious.",
        "She'll get reckless.",
        "She'll make a mistake.",
        "HR will jump on her",
        "Karen is also the kind of person…",
        "...who'll throw anyone under the bus.",
        "If it'll help her survive.",
        "I really don't like buses.",
        "Especially getting run over by them.",
        "I can't help but picture it in my head.",
"Would she try to get my soul as well?",
"I'm out there, bleeding out…",
"She, leaning over me, looking in my eyes.",
"Rex, impatiently waiting for my last breath.",
"And floating upwards, but being cut off.",
"Being janked into a container.",
"Being trapped, for all eternity.",
"As they surely wouldn't…",
"...insert my lowly soul into any new body.",
"Those are reserved for high-ups.",
"Management might want eternity…",
"...but I'm quite content with my lifespan.",
"Karen seemed quite impatient.",
"When I left the office.",
"She looked like she was going to…",
"... bite the head off anyone distracting her.",
"She kept looking at the clock.",
"Just waiting for others to leave.",
"Poor Maddy, who had the evening shift.",
"She's going to be right there…",
"...in the middle of it.",
"When shit hits the fan.",
"Karen needs to hurry if…",
"...she want to get it done tonight.",
"Robby, from HR, has contacts at the police.",
"And saving the company from bad rep…",
"...that would boost his career.",
"Rob just needs that last bit of evidence against them.",
"And an access card to the basement.",
"That's why he's been hitting on…",
"...that new chick at the office.",
"Merry's so infatuated with him.",
"She'd do anything.",
"Like hand over an exclusive card…",
"...simply because he says that he…",
"...left his own at his desk, or something.",
"And he really need a card to get…",
"...coffee from the cafeteria for the two of them.",
"She'd fall for shit like that in an instant.",
"And there! Rob has his access.",
"He smiles at Merry…",
"...who thinks she has a shot with him.",
"And Rob heads downstairs.",
"Not to the cafe of course.",
"But to the garage.",
"To the basement.",
"The card makes a peculiar pling…",
"...when it opens the lock.",
"And Rex'll be there.",
"Probably covered in blood.",
"And something in his hand…",
"...that can be used as a weapon.",
"I hope Rob has good reflexes.",
"And thenagain, I don't.",
"No witness, no worries.",
"But Rob's no fool, he's prepared.",
"He has a cell in his hand…",
"...ready to press the call.",
"If he is as smart as he seems…",
"...he'd have called the cops even before that.",
"So that they are close by, just waiting for the call.",
"Any way this goes, it's going to be ugly.",
"Glad I'm not there to see it."

    });

    public List<string> messageText = new List<string>(new string[]
    {
        "HR keeps calling me!",
        "Are they onto us?",
        "Do you know anyone at HR?",
        "Why aren't you answering any messages?!",
        "Have you heard anything from Merry?",
        "Answer me!",
        "This is an emergency!",
        "Are you home?",
        "We need you to get back to office immediately!",
        "I swear I hear the sirens already",
        "They'll get you too!",
        "So don't just ignore me!",
        "Come on, just pick up the phone!",
        "I swear I'll come knock your doors down!",
        "I'll tip HR off myself",
        "So maybe I'll have sanctuary",
        "You want in on it??",
        "I need a 'yes' right away!",
        "I got Jey onboard",
        "He just burst into my office",
        "He's flabbergasted!",
        "Never thought I'd use that word",
        "But it suits him perfect!",
        "Eyes as wide as plates, I tell you",
        "He said he was downstairs",
        "Just came from the garage",
        "Keeps repeating he saw something",
        "I don't want to know details",
        "Or we'll all end up in padded rooms",
        "Jey's hellbent on getting the boss sacked",
        "He says he won't stand for this shit",
        "Are you getting these messages at all??",
        "Helloooo??!!?!",
        "Jey's about to call the cops on corp",
        "We can't let him do that?",
        "Right??!",
        "Cops'll bust us too",
        "Drag your ass here right now!",
        "Don't leave me handle this shit alone",
        "I can't do this on my own",
        "I need you, right now!",
        "You can talk sense into him",
        "Honestly, Jey's going mental",
        "Merry just came by my cubicle",
        "She keeps talking about that Rob",
        "She actually can't shut up about him",
        "Doesn't she get what's going on??",
        "OMG!!! OMFG!!!!!!",
        "Merry gave her key to HR!!",
        "We're screwed!",
        "I'm getting out of there",
        "When you get these msgs",
        "Just run! Hide! Keep away!",
        "Oh fuckfuckfuck---",
        "Don't contact me again!",
    });

    // Start is called before the first frame update
    void Start()
    {
        curseLenght = curseText.Count;
        Debug.Log("Curses: " + curseLenght);
        messageLength = messageText.Count;
        Debug.Log("Messages: " + messageLength);
    }

    // Update is called once per frame
    void Update()
    {

    }
}
